### ISSUE TITLE
Changelog links for premium plugins are not working

### ISSUE THREAD

**Issue by JosKlever** [sprucely-designed/mainwp-discord-notifications#1]
For premium plugins (like WPBakery) the changelog link doesn't work. Only this is shown:
```[View Full Changelog]()```

The `$plugin_info['PluginURI']` is empty so the link can't be created. Maybe this can be solved with some conditional output?

**Comment by sisaacrussell** [comment]
Yeah, I've seen the same. This is a downstream issue with how there's no consistency in how plugins link changelog data. I'm limited to what MainWP sees, which is also broken for these types of plugins. We can add a conditional check to leave off that link if there's no URL, though. I'll add that in the next update.

**Comment by sisaacrussell** [comment]
Added a conditional check to several fields including this one in 1.1.1.
