### ISSUE TITLE
Updating issues

### ISSUE THREAD

**Issue by JosKlever** [sprucely-designed/mainwp-discord-notifications#11]
When Updating from 1.1.3 to 1.1.4 using Git Updater, I still get 1.1.3, so that's not working. I've tested this twice. I saw the 1.1.3 url in the details of the update (via Dashboard - Updates).

When I download 1.1.4, the folder has the version number in it, so it can't overwrite the previous version and I had to rename the folder in the zip to update.

I also see that the tags sometimes use only the version number and sometimes includes the letter v:
v1.0.0
1.1.1
1.1.2
1.1.3
v1.1.4

I'm not a Github expert (helping here helps me to learn more), but this needs to improve for consistency.

**Comment by sisaacrussell** [comment]
Thanks @JosKlever. I tested and was able to reproduce that issue. I went through and corrected the tags and re-released some of the older releases with the correct tags. Everything should be working properly now to update to v1.1.4. You may need to refresh your Git Updater cache to pull the latest version. I tested a fresh download and update on my install and it worked as expected now.,
