### ISSUE TITLE
Update via Github Updater installed develop branch instead of main one

### ISSUE THREAD

**Issue by JosKlever** [sprucely-designed/mainwp-discord-notifications#15]
Today I installed the latest update using Github Updater. It showed that it would be 1.1.5 -> 1.2.2, but it appears I got 1.3.0-beta.1 and it doesn't work anymore. I don't get notifications and there are no errors in the log.

In the settings of Github Updater I see that the default branche would be "master". However this plugin only has "main" and "develop".

I've installed version 1.2.2 now manually and the notifications are working again.

**Comment by sisaacrussell** [comment]
Thanks for reporting! More git tag shenanigans. I've removed that dev beta tag (had no idea Git Updater would pull a tag from another branch) and cleaned up all the tags. I did a test just now updating from 1.1.5 > 1.2.2 and it worked properly now.

**Comment by JosKlever** [comment]
I see Git Updater has some documentation about this, so that might help you as well:
https://git-updater.com/knowledge-base/required-headers/
https://git-updater.com/knowledge-base/versions-branches/
