### ISSUE TITLE
Fields like author and description can contain HTML, which is displayed as code

### ISSUE THREAD

**Issue by JosKlever** [sprucely-designed/mainwp-discord-notifications#2]
The plugin assumes that content of certain fields are only containing plain text, but some can contain HTML as well. Right now Discord shows the HTML code. I don't know if it can be shown as HTML or the HTML needs to be stripped?

Example:
![image](https://github.com/sprucely-designed/mainwp-discord-notifications/assets/20986647/1f46ef7c-f8ba-4c57-904d-c53cea44ee8c)

**Comment by sisaacrussell** [comment]
@JosKlever, what do you think of the changes in #7 to convert then strip?

**Comment by JosKlever** [comment]
Sounds like a good idea. Maybe skip the stripping for now, so we might catch some more examples?
