### ISSUE TITLE
Possibility to update the plugin

### ISSUE THREAD

**Issue by JosKlever** [sprucely-designed/mainwp-discord-notifications#4]
If you publish an update for your plugin, it doesn't show on the websites of your users, so have you considered an update possibility? I know another plugin that added this recently and that's working. It was handled in this commit: https://github.com/herbie4/mainwp-check-plugins-vulnerability-extension/commit/da29587696e80d63b4e6dbbed26d67cd5ba4fd00

**Comment by sisaacrussell** [comment]
If you're using Git Updater, updates are now correctly supported via that helper plugin with the latest commit. I'll add a section to the README with instructions pointing to that for now. I'll look into the functionality you linked as well.
